require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/task2s", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Task2. As you add validations to Task2, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Task2.create! valid_attributes
      get task2s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      task2 = Task2.create! valid_attributes
      get task2_url(task2)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_task2_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      task2 = Task2.create! valid_attributes
      get edit_task2_url(task2)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Task2" do
        expect {
          post task2s_url, params: { task2: valid_attributes }
        }.to change(Task2, :count).by(1)
      end

      it "redirects to the created task2" do
        post task2s_url, params: { task2: valid_attributes }
        expect(response).to redirect_to(task2_url(Task2.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Task2" do
        expect {
          post task2s_url, params: { task2: invalid_attributes }
        }.to change(Task2, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post task2s_url, params: { task2: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested task2" do
        task2 = Task2.create! valid_attributes
        patch task2_url(task2), params: { task2: new_attributes }
        task2.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the task2" do
        task2 = Task2.create! valid_attributes
        patch task2_url(task2), params: { task2: new_attributes }
        task2.reload
        expect(response).to redirect_to(task2_url(task2))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        task2 = Task2.create! valid_attributes
        patch task2_url(task2), params: { task2: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested task2" do
      task2 = Task2.create! valid_attributes
      expect {
        delete task2_url(task2)
      }.to change(Task2, :count).by(-1)
    end

    it "redirects to the task2s list" do
      task2 = Task2.create! valid_attributes
      delete task2_url(task2)
      expect(response).to redirect_to(task2s_url)
    end
  end
end
